apiVersion: v1
kind: Service
metadata:
  name: pet-clinics-service
spec:
  selector:
    app: pet-clinics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodeport: 31000
  type: NodePort
  
  
  
